### ISSUE TITLE
Siirtyminen takaisin sovelluksessa

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#13]
Kun jokin ikkuna on auki ja haluaisin siirtyä edelliseen auki olleeseen ikkunaan, niin painamalla puhelimessa olevaa "takaisin" nappulaa, ei siirry edelliseen ikkunaan, vaan jonnekin muualle.

**Comment by TeemuS96** [comment]
Pystytkö yhtään avaamaan enemmän, että missä ruuduissa tämä tapahtuu vai tapahtuuko kaikkialla jotta voimme "toistaa" skenaarion ja korjata sen.

**Comment by TarjaS** [comment]
Piikissä on eri välilehtiä eli kun olen välilehdellä, jossa on pylväsdiagrammi ja siirryn siitä kuvan ottoon ja sen jälkeen painan "takaisin" nappulaa, avautuu näyttö, jossa on kuittien kuvat ja niiden tilat. Sinänsä tämä voi olla ihan hyväkin, jotta ei tarvitse kahta kertaa painaa "takaisin" nappulaa. Olisi hyvä, että välilehdet korostuisivat (eri väri?) sen mukaan millä välilehdellä olen, koska nyt ovat niin saman näköisiä.
Toinen kohta jossa "takaisin" ei toimi, on se suodatin, sillä sehän sulkeutuu vain painamalla suodatinta uudestaan. Voisi siis sulkeutua, kun painaa "takaisin".

**Comment by joonassalojarvi** [comment]
Tämä korjattu tulevaan julkaisuun, kuitin muokkasnäkymästä siirrytään aina takaisin siihen ruutuun, mistä on siihen tultu (paitsi kuittia tallentaessa, jolloin siirrytään edelleen kuittilistaukseen). Lisäksi suodattimet sulkeutuvat takaisin-nappulasta. Alapalkkiin laitetaan kirkkaampi väri valitulle välilehdelle.
