### ISSUE TITLE
Piikki kaatuu Työ seurantakohteen valitsemalla

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#14]
[Piikki ja Työ.docx](https://github.com/OscarSoftware/OscarPiikkiPublicIssues/files/3470514/Piikki.ja.Tyo.docx)

**Comment by joonassalojarvi** [comment]
Duplikaatti
https://github.com/OscarSoftware/OscarPiikkiPublicIssues/issues/3
