### ISSUE TITLE
Tili haku

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#15]
Kun tiliä hakee Muut matkakulut nimellä, ei se tule listan ylimmäksi. Kun hakee Matkakulut, saa melko pian näkyviin listalla myös Muut matkakulut. Voisiko haku siis tarjota parasta matchiä suoraan ja vasta sen jälkeen muita vaihtoehtoja?

**Comment by phyytinen** [comment]
Korjattu hakemaan parhaat matchit ylimmäksi. Rankkaus-painotukset löytyvät täältä: https://www.npmjs.com/package/match-sorter kohdasta "This solution".

**Comment by AnnikaP** [comment]
Kun menee valitsemaan tiliä, niin tällä hetkellä tilien järjestys on ilmeisesti tilikartan tilinumeron mukainen. Koska tilinumeroita ei kuitenkaan piikin puolella näy niin itse ajattelisin, että olisi järkevämpää järjestää tili aakkosjärjestykseen. Silloin olisi käyttäjän helpompi selailla sopivaa tiliä jos ei itse tiedä yhtään mihin aikoo kuitin tiliöidä ja ei siten osaa hakuun laittaa mitään hakusanaa.
