### ISSUE TITLE
Lisäkenttä

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#16]
Piikkiin tarvittaisiin lisäkenttä esimerkiksi nimeltään Lisätieto.
Selite kenttä on tieto, jonka on tarkoitus siirtyä kirjanpidon tositteelle, mutta tämä Lisätieto jäisi vain Kuittien käsittely toimintoon nähtäväksi.
Lisätieto kenttää käytettäisiin esimerkiksi ilmoittamaan ketkä henkilöt ovat olleet läsnä lounaalla eli siksi sen paikka olisi hyvä olla selitteen jälkeen.

**Comment by TeemuS96** [comment]
Muutetaan Kuvaus kenttä mobiilissa Selite kentäksi, ja laitetaan mukaan Lisäkuvaus saraketta varten uusi kenttä.

**Comment by joonassalojarvi** [comment]
Lisätty lisätieto kenttä, kuvaus kenttä muutettu selite-kentäksi.
