### ISSUE TITLE
Negatiivinen summa sallituksi

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#19]
Pro:ssa voi summan muuttaa negatiiviseksi kuitin rivillä. Voisiko kuitille syöttää Piikissä negatiivisen hinnan kuitenkin niin, että kokonaissumma on positiivinen? Esimerkiksi pullon palautus, kun kuitilla on muita ostoja eri alv-koodilla.

**Comment by joonassalojarvi** [comment]
Onko tarkoitus, että kokonaissumma pitäisi olla positiivinen aina? Onko esimerkiksi mahdollista, että Piikkiin lisätään kuitti jonka loppusumma on negatiivinen? Esim. hyvityskuitit. 

Voidaan laittaa ominaisuutena negatiivisen hinnan laitto, ja samalla onnistuisi negatiivinen loppusumma jos sille on tarvetta.

**Comment by TarjaS** [comment]
Jos sallittaisiin, että kokonaissumma on negatiivinen, niin voitaisiinko summa saada Piikissä punaiseksi, jotta se näkyisi selkeästi? Negatiivisuus on kuitenkin poikkeus ja silloin huomaisi asian helpommin, että ei käy niin, että kuitti menee vahingossa negatiiviseksi.

**Comment by joonassalojarvi** [comment]
Korjattu
