### ISSUE TITLE
Tilin haku, ei tuloksia

### ISSUE THREAD

**Issue by AnnikaP** [OscarSoftware/OscarPiikkiPublicIssues#20]
Kun menee hakemaan tiliä ja kyseisellä haulla ei löydyt tuloksia saa vastauksen 'Sorry, no results'. Sovellus muutenkin suomeksi, joten muutetaan tuokin suomeksi.

**Comment by AnnikaP** [comment]
Tähän voisi lisätä, että Tilin alasvetovalikossa lukee 'Select' kun taas Seurantakohteiden alasvetovalikossa lukee 'Valitse'. Koska sovellus suomeksi niin varmaan muutetaan tuon Tilin alasvetovalikon teksi suomeksi.

**Comment by joonassalojarvi** [comment]
Tämä on korjattu seuraavaan versioon
