### ISSUE TITLE
Uusien kuittien oletusarvot

### ISSUE THREAD

**Issue by AnnikaP** [OscarSoftware/OscarPiikkiPublicIssues#21]
Lisäsin itselleni arvot uusien kuittien oletusarvoihin. Sovellus tuo sinne määritellyt tiedot hienosti uudelle kuitille. 

-Jos haluaa muuttaa oletuksena tulleita seurantakohteita niin sovellus kaatuu tai antaa virheilmoituksen 'Something went wrong. Sorry about that. Press the reload button to try again.' Reloadin painamisen jälkeen sovellus kaatuu.

- Uuden kuitin luonnissa kaikki häviää. Mikäli jo lähetettyä kuittia muokkaa tulee virheilmoitus 'Something went wrong. Sorry about that. Press the reload button to try again.' (Pitäisikö olla suomeksi kun sovelluskin on?) Reloadin painamisen jälkeen sovellus kaatuu.

Mielestäni pitää olla kuitenkin mahdollisuus muuttaa seurantakohteita muuksi kuin oletukseksi. Toki jossain yrityksissä voi olla, että kaikki kulut menevät aina samoille seurantakohteille. Pitäisikö tässä olla olemassa joku valinta onko oletusseurantakohteita mahdollista muuttaa? Oli kummin vain, niin sovelluksen kaatuminen on estettävä.

**Comment by phyytinen** [comment]
Ei pystytty toistamaan virhettä nykyisellä kehityksessä olevalla versiolla, jossa seurantakohteiden valinta on tehty täysin uusiksi. Uudessa päivityksessä tulee täten korjaus asiaan!
