### ISSUE TITLE
Piikin maksutapa

### ISSUE THREAD

**Issue by AnnikaP** [OscarSoftware/OscarPiikkiPublicIssues#25]
Piikin maksutapoihin nousee nyt Pron puolelta Myynnin maksutapojen ylläpidosta ne maksutavat joille ole määritelty mitään tyyppiä. (Käteissuoritus, Luottokorttisuoritus, Pankkikorttisuoritus) Eikös sinne perustettu uus tyyppi 'Piikki' sitä varten, että sillä merkityt nousisivat Piikin maksutavoiksi. Nythän sinne nousee myynnissä käytettäviä maksutapoja.

**Comment by TeemuS96** [comment]
Joo tämä sekä #26 johtuvat siitä, että olimme laittaneet noi haut jo Piikkiin ennenkuin noita muutoksia oli tehty. Laitetaan noiden haku uusiksi seuraavaan hotfixiin niin, että haetaan vain piikin käytössä olevat

**Comment by TeemuS96** [comment]
Tämä hoidettu. Tulee seuraavaan päivitykseen.
