### ISSUE TITLE
Piikin tilikartta

### ISSUE THREAD

**Issue by AnnikaP** [OscarSoftware/OscarPiikkiPublicIssues#26]
Pron puolelle on Tilien ylläpitoon on tehty uusi sarake 'Tili käytössä Piikissä' ja olen sinne valinnut joitakin tilejä siirrettäväksi piikkiin. Piikissä näkyy vielä koko tilikartta. Eikö toimintoa ole vielä otettu Piikin puolella käyttöön?

**Comment by TeemuS96** [comment]
Tehty. Tulee seuraavaan päivitykseen
