### ISSUE TITLE
Selite

### ISSUE THREAD

**Issue by AnnikaP** [OscarSoftware/OscarPiikkiPublicIssues#27]
- Selite-kenttää ei ole määritelty pakolliseksi. Tämä kenttä tulisi määritellä pakolliseksi. Asiasta on keskusteltu Tapiolan Marin sekä Talouden projektipäälliköiden kanssa. Kirjanpitäjän työtä helpottava pakollisuus sekä lisäksi esim. edustuskuluissa on aina ilmoitettava osallistujat.

Koska Selite kenttään sopii melkoisen paljon merkkejä, niin kentän korkeutta voisi lisätä niin, että käyttäjä näkisin kerralla kaiken mitä on kirjoittanut. Tällä hetkellä kenttä on vain yhden rivin korkuinen.

**Comment by phyytinen** [comment]
Selitekenttä asetettu pakolliseksi. Nyt myös selite- ja lisäkuvauskentän koko muuttuu dynaamisesti tekstin korkeuden mukaan. Tulee seuraavaan päivitykseen.
