### ISSUE TITLE
T1009-005 V-Eräseurattava työnumero

### ISSUE THREAD

**Issue by TeemuS96** [OscarSoftware/OscarPiikkiPublicIssues#3]
Kyseistä työnumeroa valittaessa softa kaatuu. Selvitetään mikä case

**Comment by joonassalojarvi** [comment]
Taskien itse riville tullut backendiin vahingossa sama uniqueId kuin ekalle itemille. Ongelma korjaantuu kun uusi valitsin saadaan valmiiksi fronttiin, ja uniqueId voidaan poistaa käytöstä.

**Comment by joonassalojarvi** [comment]
Korjattu
