### ISSUE TITLE
Kuitin hintarivit näkyvät tilastoissa erillisinä kuitteina

### ISSUE THREAD

**Issue by phyytinen** [OscarSoftware/OscarPiikkiPublicIssues#31]
Jos kuitilla on monta hintariviä, niin tilastot näyttävät että kuitteja olisi lisätty enemmän kuin niitä todellisuudessa on olemassa. Jokainen hintarivi siis katsotaan tilastoissa erilliseksi kuitiksi.

**Comment by joonassalojarvi** [comment]
Fixed
