### ISSUE TITLE
Kuva rajautuu väärin

### ISSUE THREAD

**Issue by toukoks** [OscarSoftware/OscarPiikkiPublicIssues#4]
Kun ottaa kuvan ja yrittää cropata siitä pienen osan, tulee lopputulokseksi väärin cropattu kuva. Puhelin Nokia 7 Plus.

### Croppausvalinta:
![Screenshot_20190726-151754](https://user-images.githubusercontent.com/37538165/61951161-d42be300-afb8-11e9-9920-6dece97a7bcf.png)

### Lopputulos:
![Screenshot_20190726-151809](https://user-images.githubusercontent.com/37538165/61951170-de4de180-afb8-11e9-97eb-7f7439cc610c.png)

**Comment by phyytinen** [comment]
Korjattu. Croppausta edeltävä kutsu Image.getSize palautti väärän kuvakoon androidille. Koko otettu nyt suoraan kuvaobjektin width/height propertyistä.
