### ISSUE TITLE
Päänäkymän kaavio ei lataudu uudestaan

### ISSUE THREAD

**Issue by TeemuS96** [OscarSoftware/OscarPiikkiPublicIssues#5]
Kun kirjaudutaan sisään Piikkiin, päänäkymän chartti toimii normaalisti. Mutta kun Piikin sulkee ja käynnistää uudestaan(kirjautuu automaattisesti), ei tuo chartti enää toimi. Kun käyttäjä kirjautuu ulos ja takaisin sisään, se toimii taas normaalisti.

**Comment by joonassalojarvi** [comment]
View komponentin onLayout funktio ei toiminut oikealla tavalla. Korkeuden asettaminen korvattu hieman staattisemmalla vaihtoehdolla, jolla arvot ovat saatavilla heti käynnistyksen jälkeen `(Dimensions.get('window').height`
