### ISSUE TITLE
Asetuksien vaihto näkyy EditReceiptScreenissä vain ensimmäisen muutoksen jälkeen

### ISSUE THREAD

**Issue by phyytinen** [OscarSoftware/OscarPiikkiPublicIssues#6]
Kuittien oletusarvojen vaihto asetuksista heijastuu EditReceiptScreeniin vain ensimmäisellä kerralla, Uudelleenvaihdon jälkeen ruudussa näkyy edelleen vanhat tiedot.

**Comment by joonassalojarvi** [comment]
Kuitti ei päivittynyt, sillä siirryttäessä muokkausnäkymään navigaation Receipt parametri oli null, ja kyseinen ruutu päivittää itsensä vain, jos parametri on eri kuin edellisellä. Näin ollen vertailussa null === null, mikäli ei välissä siirrytty toisen kuitin tietoihin tai käynnistetty appia uudelleen.

Vika korjattu toistaiseksi willFocus funktiossa luomalla uusi kuitti joka kerta, kun Receipt parametri on null. Otettu huomioon myös back buttonin käyttö liikuttaessa muokkasnäkymän ja kameran välillä, jotta tiedot eivät poistu.

Toisenlainen, paranneltu ratkaisu tulossa seuraavassa versiossa.
