### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#7]
Kuitti luotu Piikissä ja lähetetty. Sen jälkeen tehty Pro:ssa tositteeksi.
Kun uudestaan katsottu Piikkiä, Piikki Offline tilassa ja kuitin status edelleen Kirjattu.
Suljettu väkin Piikki ja kun uudestaan avattu, ei Offlline tilaa ja Viety tositteeksi tieto päivittynyt.

Kokeiltu, että ei anna kuitenkaan muuttaa kuitin tietoja, vaikka tila Kirjattu.

**Comment by TeemuS96** [comment]
Saatko toistettua tätä onglemaa mitenkään? Mikäli saat niin saataisiinko "step by step" ohjeet ongelman toistamiseksi. Tuo offline tila saattaa johtua niin monesta asiasta, että epäilen että se ei välttämättä ole itse Piikin mobiilikoodiin liittyvä asia.

**Comment by joonassalojarvi** [comment]
Kuitin muokkaaminen on lukittu offline tilassa/jos kuittia ei saada haettua palvelimelta, jotta ei satu mitään ristiriitoja palvelimen ja puhelimen välillä. 

Kuitit eivät automaattisesti päivity, muuten kuin käynnistyksen yhteydessä, tai jos vetää alas listanäkymästä kuittien päivittämiseksi.

Sitä on vaikea sanoa, miksi Piikki mennyt offline tilaan. Piikki siirtyy offline tilaan, jos puhelimessa ei ole yhteyttä, tai jos kuittien päivittäminen epäonnistuu. Jos puhelimessa kuitenkin on yhteys ja listan alasvetäminen ei auta, todennäköisesti Piikin palvelimessa on jotain häikkää.

**Comment by AnnikaP** [comment]
Minulla ladattuna 3.1. Jostain syystä on offlinessa heti kun kirjauduin sisään sovellukseen. Ei auttanut vaikka poistin sovelluksen ja latasin uudestaan. Puhelimessa on nettiyhteys toiminnassa. Miten pääsisin pois tuosta tilasta ja testaamaan tätä?

**Comment by TeemuS96** [comment]
@AnnikaP 

Aloin selvittämään tätä ja huomasin että pankkitesti kannassa olevalle YKAYTT sinun tunnuksen tietueelle ei oltu määritelty WINNAME kenttään mitään. Tuota kenttää piikki käyttää hakeakseen käyttäjän AD tunnusta vastaan. Kävin laittamassa sen sinne, niin nyt pitäisi toimia. Laitan tiketin tästä että ilmoitetaan käyttäjälle vähän tarkemmin näistä kirjautumiseen liittyvistä ongelmista.
