### ISSUE TITLE
Sessiosi vanhentunut

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#8]
Latasin Piikki sovelluksen noin 10:00. Sen jälkeen lähetin kuitin ja käsittelin sitä Pro:ssa.
Kun klikkasin puhelimen näytön taas aktiiviseksi 11:23 nähdäkseni Piikin, niin sain ilmoituksen Sessiosi vanhentunut, kirjaudu uudestaan sisään.

Tein näin ja sitten taas pelitti.

**Comment by joonassalojarvi** [comment]
Tämä korjattu nyt. Yhdestä funktion kutsusta puuttui parametrinä refresh tokeni, jolloin access tokenia ei voitu päivittää kutsujen yhteydessä.
