### ISSUE TITLE
Lisää hintarivi ja kursori

### ISSUE THREAD

**Issue by TarjaS** [OscarSoftware/OscarPiikkiPublicIssues#9]
Kun painaa Lisää hintarivi nappulaa, kursori ei siirry suoraan Hinta 2* kenttään, vaan jää kuvan alareunaan. Koska hinta pakollinen kenttä, olisi käyttäjäystävällistä, jos kursori vilkkuisi siinä heti.

**Comment by TeemuS96** [comment]
Nyt kun painetaan "Lisää hintarivi" -nappulaa niin näkymä scrollaantuu automaattisesti uuden hintarivin kohdalle, mutta päätin olla laittamatta automaattista focusta.
